### ISSUE TITLE
Not sure what I'm doing...

### ISSUE THREAD

**Issue by rileyil77** [Gualdimar/fsd4ever#2]
I downloaded the fsd4ever server and the fsd4ever.  I like the idea of the custom server, because for some reason, since I switched routers, my R-JTAG XBox 360 Phat won't connect outside my network.  So if I need a cover I can download it and place it on my own local server.  However I'm not sure what I'm doing.  I opened http://192.168.1.3/xbox360/cover.php in Chrome and got this:

( ! ) Notice: Undefined index: id in X:\myserverhtmlroot\xbox360\cover.php on line 2
Call Stack
#	Time	Memory	Function	Location
1	0.0027	138064	{main}( )	...\cover.php:0

( ! ) Notice: Undefined index: query in X:\myserverhtmlroot\xbox360\cover.php on line 3
Call Stack
#	Time	Memory	Function	Location
1	0.0027	138064	{main}( )	...\cover.php:0

( ! ) Notice: Undefined index: query in X:\myserverhtmlroot\xbox360\cover.php on line 19
Call Stack
#	Time	Memory	Function	Location
1	0.0027	138064	{main}( )	...\cover.php:0

I've not changed anything in the cover.php; so this is my cover.php.

<?php

$titleid=$_GET['id'];

if($_GET['query'] == "TitleID")

{

		$ch = curl_init();

		$options = [

		    CURLOPT_SSL_VERIFYPEER => false,

		    CURLOPT_RETURNTRANSFER => true,

		    CURLOPT_URL            => 'http://xboxunity.net/api/Covers/'.$titleid

		];

		

		curl_setopt_array($ch, $options);

		$data = json_decode(curl_exec($ch));

		curl_close($ch);

		

		cover($data);

}

elseif($_GET['query'] == "SearchTerm")

{

	$ch = curl_init();

	$options = [

	    CURLOPT_SSL_VERIFYPEER => false,

	    CURLOPT_RETURNTRANSFER => true,

	    CURLOPT_URL            => 'http://xboxunity.net/api/Covers/00000000/'.str_replace(",", " ", $titleid)

	];

	

	curl_setopt_array($ch, $options);

	$data = json_decode(curl_exec($ch));

	curl_close($ch);

	

	cover($data);

}

function cover($data)

{

	$xml = new SimpleXMLElement('<?xml version="1.0" encoding="ISO-8859-1"?>'.'<covers/>');

		

	if(count($data)>0)

	{

		foreach ($data as &$value) {		

		    $title = $xml->addChild('title');

		    $title->addAttribute('id',$value->titleid);

		    $title->addAttribute('name',$value->name);

		    $title->addAttribute('mediaid','');

		    $title->addAttribute('filename','Cover.png');

		    $title->addAttribute('type','');

		    $title->addAttribute('mainlink',$value->url);

		    $title->addAttribute('front',$value->front);

		    $title->addAttribute('Official',(int)$value->official);    

		}

	}

	

	Header('Content-type: text/xml');

	print($xml->asXML());

}

?>

What am I doing wrong?

**Comment by Gualdimar** [comment]
you don`t need to open this in your browser: http://192.168.1.3/xbox360/cover.php
you need to user patcher (fsd4ever.exe) to generate pathced fsd xex with this links

**Comment by rileyil77** [comment]
Yeah, I figured it out.  I felt stupid after asking and figuring it out about 10 minutes later.  Great product.
