### ISSUE TITLE
Use with updated default.xex/weather support

### ISSUE THREAD

**Issue by Casuallynoted** [Gualdimar/fsd4ever#3]
Hello!

Is there any chance we might see this updated for the latest unofficial release (with lots of bugfixes and crash preventions)?
https://cdn.octalsconsoleshop.com/FSD3-783.rar

Also, is there any chance we might see a fix for the weather function as well?

**Comment by Gualdimar** [comment]
783 release doesn`t have any "bugfixes and crash preventions", so there is no point in your request.
you can read more here: https://www.realmodscene.com/index.php?/topic/6295-freestyle-30-rev-780783-not-official/
weather is dead 4ever
